### ISSUE TITLE
Regarding the issue with YouTube-AD-Blocker enabled

### ISSUE THREAD

**Issue by CHIHOLUEN** [iamfugui/YouTube-AD-Blocker#1]
Hi, fugui. I've been using YouTube-AD-Blocker without any issues until today when I encountered a problem. After enabling the plugin, the video chapters on the right side of YouTube no longer function properly. Is there a way to fix this? Thanks.

**Comment by iamfugui** [comment]
Sorry, I just noticed your question now. This issue was caused by incorrect CSS styles and has been addressed in the latest code update.

**Comment by CHIHOLUEN** [comment]
OK, thank you for helping me figure it out. thank you for your time.
