### ISSUE TITLE
To install directly from GitHub Raw button, rename index.js to index.user.js

### ISSUE THREAD

**Issue by ner00** [iamfugui/YouTube-AD-Blocker#2]
Hi.

I use TamperMonkey, and if scripts are not named `*.user.js` it doesn't pick them up automatically for installation when you click on the [Raw](https://raw.githubusercontent.com/iamfugui/YouTube-AD-Blocker/main/index.js) link; I expect other extensions like GreaseMonkey or ViolentMonkey to work the same but unsure. So my request is to rename the file [index.js](https://raw.githubusercontent.com/iamfugui/YouTube-AD-Blocker/main/index.js) to [index.user.js](https://raw.githubusercontent.com/ner00/YouTube-AD-Blocker/main/index.user.js)

Thank you.

**Comment by iamfugui** [comment]
Ok, but you can also install the script on greasyfork.

https://greasyfork.org/zh-CN/scripts/459541-youtube%E5%8E%BB%E5%B9%BF%E5%91%8A-youtube-ad-blocker

**Comment by ner00** [comment]
Yes, I know, and that is part of my point. The GreasyFork install button also links to a script that ends with `*.user.js` for the same reason.
